* Game with motion-captured animation for the TI-99/4A home computer.
*
* Copyright (c) 2024 Eric Lafortune
*
* This program is free software; you can redistribute it and/or modify it
* under the terms of the GNU General Public License as published by the Free
* Software Foundation; either version 2 of the License, or (at your option)
* any later version.
*
* This program is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
* FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
* more details.
*
* You should have received a copy of the GNU General Public License along
* with this program; if not, write to the Free Software Foundation, Inc.,
* 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA

    copy "include/cpu.asm"
    copy "include/vdp.asm"
    copy "include/colors.asm"
    copy "include/sound.asm"
    copy "include/speech.asm"
    copy "include/cru.asm"
    copy "include/mouse.asm"
    copy "include/swap_macros.asm"

    copy "initialize_graphics.asm"
    copy "draw_parachute.asm"
    copy "draw_landscape.asm"
    copy "draw_player.asm"
    copy "draw_objects.asm"
    copy "player_health_macros.asm"
    copy "update_player.asm"
    copy "check_input.asm"
    copy "update_objects.asm"
    copy "ordinates.asm"
    copy "optimize_objects.asm"
    copy "video_macros.asm"
    copy "blit_macros.asm"
    copy "sound_macros.asm"
    copy "music_macros.asm"
    copy "speech_macros.asm"
    copy "../out/sprite_names.asm" ; Generated by the build process.

* Start in module ROM.
    aorg module_memory

* Module header.
module_start
    byte >aa                   ; Header.
    byte 1                     ; Version.
    byte 1                     ; Number of programs.
    byte 0                     ; Unused.
    data 0                     ; Power-up list.
    data program_list          ; Program list (shown in reverse order).
    data 0                     ; DSR list.
    data 0                     ; Subprogram list.

* First element of the program list.
program_list
    data 0                     ; Next element.
    data program_start         ; Program start.
    stri 'STEALTH RUNNER'      ; Program name.
    even

* A single workspace at the end of scratch-pad RAM.
workspace equ scratchpad_end - workspace_size

* The entry point of the program.
program_start
    limi 0
    lwpi workspace

* Copy the main game code to expansion RAM.
    .switch_bank @code_bank    ; The main code is in the code bank.
    .copy_memory module_memory, expansion_code_end, low_expansion_memory

* Continue running the code from expansion RAM, so we can switch between
* module memory banks more easily.
    b    @expansion_code

expansion_code_start
    xorg $ - module_memory + low_expansion_memory
expansion_code

* Cache some I/O addresses in registers.
;   .spchrd_in_register r9     ; Cache the speech read address.
;   .spchwt_in_register r10    ; Cache the speech write address.
;   .sound_in_register  r13    ; Cache the sound address.
    .vdpwa_in_register  r14    ; Cache the VDP address write address.
    .vdpwd_in_register  r15    ; Cache the VDP data write address.

* Initialize the input, checking whether a mouse is present.
    .initialize_input

* Copy the video player code to scratchpad RAM, for better performance.
play_intro_video
    .switch_bank @data_bank    ; The player code is in the data bank.
    .copy_memory video_code_start, video_code_end, scratchpad

* Play the intro video.
    .initialize_video_graphics

    li   r0, intro_video_bank
    bl   @play_video

* Wait for a key press (in key column 0).
    li   r12, cru_write_keyboard_column
    clr  r0
    ldcr r0, cru_keyboard_column_bit_count
    li   r12, cru_read_keyboard_rows

key_press_loop
    stcr r0, cru_read_keyboard_row_bit_count
    ci   r0, >ff00
    jeq  key_press_loop

* Silence all sound.
    .silence_sound_generator 0
    .silence_sound_generator 1
    .silence_sound_generator 2
    .silence_sound_generator 3

* Copy the VDP blitting code to scratchpad RAM, for better performance.
    .switch_bank @data_bank    ; The blitting code is in the data bank.
    .copy_memory blit_code_start, blit_code_end, scratchpad

* Start the game from the world data.
play_game

* Initialize the player and the objects from the world data.
    .switch_bank @landscape_objects_bank
    li   r0, module_memory

    .initialize_player
    .initialize_player_weapons
    .initialize_objects

* Save the initial states as a save point.
    .save_player_state
    .save_player_weapon_states
    .save_object_states

* Initialize the supersprite/quadsprite cache.
    bl   @initialize_quadsprites

* Keep track of even/odd frames.
    clr  @frame_timestamp

* Animate the player parachuting in.
parachute_intro

* Restore the initial states of the most recent save point.
    .restore_player_state
    .restore_player_weapon_states
    .restore_object_states

    .reset_player
    .reset_launched_weapons
    .initialize_landscape

* Reset the graphics.
    .switch_bank @data_bank    ; The graphics are in the data bank.
    .initialize_game_graphics

* Reset the sound pointers.
    seto @current_tone0
    seto @current_tone1
    seto @current_tone2
    seto @current_noise

* Set the music pointer to start the parachuting sound.
    .start_music parachuting_sound

* Reset the speech pointer.
    clr  @current_speech
    clr  @current_speech_length
    seto @message_spoken

* Start the parachuting.
    .initalize_parachute

parachute_x_loop
    .draw_landscape_characters ; Draw the landscape deltas scrolling into view
                               ; horizontally, to get the non-edge characters
                               ; right.
     inc  @player_x                  ; Scroll right until we've reached the
     c    @player_x, @saved_player_x ; vertical starting line.
     jl   parachute_x_loop

parachute_y_loop
    .draw_parachute            ; Draw the player parachuting into view.
    .draw_landscape_delta      ; Draw the landscape scrolling into view.
    .fade_in_landscape_colors  ; Fade in the landscape colors from black

    andi r0, >000f             ; Update the sound effects at a slow pace.
    jne  skip_music_updates
    .play_music
skip_music_updates

    .wait_for_vsync

     inc  @frame_timestamp     ; Update the time stamp.

     inc  @player_y                  ; Scroll down until we've reached the
     c    @player_y, @saved_player_y ; starting point.
     jhe  parachute_intro_end
     b    @parachute_y_loop
parachute_intro_end

* Set the music pointer to mute the parachuting sound.
    .start_music mute_all


* The main game loop.
game_loop
    mov  @frame_timestamp, r0  ; Even or odd frame (at 60 Hz)?
    srl  r0, 1
    jnc  !                     ; Even frame: draw the background
    b    @draw_player          ; Odd frame:  draw the player.
!
* Draw and update the objects and the landscape (at 30 Hz).
    .draw_objects
    .draw_landscape_delta
    .update_objects

    b    @play_speech

* Draw and update the player (at 30 Hz).
draw_player
    .draw_player
    .update_player
    .check_input

* Check if any of the quit keys is pressed (at 30 Hz).
* The order is chosen so the jumps don't go out of range.
check_quit
    .test_keyboard 0, 0        ; Pressing '=' = <Quit>?
    jeq  !
    blwp @0                    ; Then quit.
!
    .test_keyboard 4, 3        ; Pressing '6' = <Proceed>?
    jeq  !!!!
!   .test_keyboard_row 3       ; Wait until '6' is released.
    jne  -!
!   .test_keyboard_row 3       ; Pause until '6' is pressed again.
    jeq  -!
!   .test_keyboard_row 3       ; Wait until '6' is released again.
    jne  -!
!
    .test_keyboard 3, 3        ; Pressing '7' = <Aid>?
    jne  restore_savepoint     ; Then continue from the last save point.
!
    .test_keyboard 1, 3        ; Pressing '9' = <Back>?
    jne  return_to_intro       ; Then restart from the intro video.

    .test_keyboard 2, 3        ; Pressing '8' = <Redo>?
    jne  next_game             ; Then restart the game.


* Play any music and speech (at 60 Hz).
play_speech
    inc  @frame_timestamp      ; Update the frame counter (for the graphics).

    .play_music
    .play_speech

* Wait for the Vsync, while checking the speech buffer if necessary,
* and continue the game loop.
    mov  r1, r1                ; Do we still have any speech data to send
    jeq  wait_for_vsync        ; to the speech buffer when it goes low?

wait_for_speech_and_vsync                   ; A bit of a hack: jump back into
    .wait_for_vsync check_additional_speech ; the speech buffer checking code
    b    @game_loop                         ; while waiting for the Vsync.

wait_for_vsync                              ; Otherwise simply wait for the
    .wait_for_vsync                         ; Vsync.
    b    @game_loop

* Continue from the last save point.
restore_savepoint
    b    @parachute_intro

* Continue with a new game.
next_game
    b    @play_game

* Return to the intro video.
return_to_intro
    b    @play_intro_video

* Various subroutines.
    copy "player_health.asm"
    copy "supersprites.asm"
    copy "directions.asm"

expansion_data_start
    aorg
expansion_code_end

    .ifgt  $, >8000
    .error 'Program code too large for first memory bank.'
    .endif

    .print 'Unused bytes in main code bank:', >8000 - $
    .next_bank

* Banks with scratchpad code, data for the intro video, graphics, levels,...
;data

* Video player subroutine, run from scratchpad RAM, for speed and to be able to
* switch between memory banks.
    xorg module_memory
video_code_start
    xorg scratchpad

    copy "video.asm"

    .print 'Unused bytes in scratchpad after video player code:', workspace - $

    .ifgt  $, workspace
    .error 'Video player code too large for scratchpad'
    .endif

    aorg
    xorg $ - module_memory_size
video_code_end

* Blitting subroutines, run from scratchpad RAM, for speed and to be able to
* switch between memory banks.
blit_code_start
    xorg scratchpad

    copy "blit.asm"

    ; Also, a tiny speech subroutine that has to be run from scratchpad RAM.
    .speech_read_status_byte_subroutine

    .print 'Unused bytes in scratchpad after blitting code:', workspace - $

    .ifgt  $, workspace
    .error 'Blitting code too large for scratchpad'
    .endif

* Global variables in scratchpad RAM, for speed.
    dorg $

* Quadsprite counter.
vdp_quadsprite_counter data 0

* Video frame counter.
frame_timestamp data 0 ; Counter for the current frame
                       ; (used for caching and even/odd tests).

* Sound variables.
current_tones
current_tone0 data 0 ; The start address of the currently playing tone 0.
current_tone1 data 0 ; The start address of the currently playing tone 1.
current_tone2 data 0 ; The start address of the currently playing tone 2.
current_noise data 0 ; The start address of the currently playing noise.

* Music variables.
current_music data 0 ; The address of the music data currently being played.

* Speech variables.
current_speech        data 0 ; The address of the speech data currently being spoken.
current_speech_length data 0 ; The address of the speech data currently being spoken.

message_spoken        data -1 ; The lowest spoken message number.

* Player variables. The coordinates are those of the top-left corner of the
* screen in the world. The player is centered on the screen, with his base
* at (128,112) expressed in pixels.
player_state
player_x               data 0 ; X ordinate, expressed in pixels.
player_y               data 0 ; Y ordinate, expressed in pixels.
player_health          data 0 ; Health (>ff00 .. >02ff).
player_state_end

player_fx              data 0 ; Fractional x ordinate (fixed point 16.16 bits).
player_fy              data 0 ; Fractional y ordinate (fixed point 16.16 bits).
player_speed           data 0 ; Speed (=motion) (-2 for dying, -1 for crouching, 0 for standing,...)
player_direction       data 0 ; Direction (=orientation) (0..15).
player_direction_delta data 0 ; Preferential initial direction delta (-1 or 1).

* Player display variables.
player_animation_bank          data 0 ; Animation memory bank (>6000, >6002,...).
previous_player_animation_bank data 0
player_frame                   data 0 ; Animation frame (0..n-1).
previous_player_frame          data 0

player_state_size equ player_state_end - player_state

    .print 'Unused bytes in scratchpad after data:', workspace - $

    .ifgt  $, workspace
    .error 'Blitting code too large for data'
    .endif

    aorg
    xorg $ - module_memory_size
blit_code_end

;data
    copy "direction_data.asm"
    copy "parabola_data.asm"
    copy "motion_data.asm"
    copy "graphics_data.asm"
    copy "sound_data.asm"
    copy "music_data.asm"
    aorg
    .next_bank

;intro_video
    bcopy "../out/intro.tms"
    .next_bank
;player_animations
    bcopy "../out/player.dat"
;landscape_objects
    bcopy "../out/levels/00_objects.dat"
    .next_bank
;out/levels/00_landscape
    bcopy "../out/levels/00_landscape.dat"
    ;.next_bank
;out/levels/00_mask
    bcopy "../out/levels/00_mask.dat"
    .next_bank
;sprite_bounds
    bcopy "../out/sprite_bounds.dat"
    .next_bank
;sprite_index
    bcopy "../out/sprite_index.dat"
    .next_bank
;sprite_positions
    bcopy "../out/sprite_positions.dat"
    .next_bank
;sprite_patterns
    bcopy "../out/sprite_patterns.dat"
    .next_bank
;speech_data
    xorg module_memory
    copy "speech_data.asm"
    aorg
    .next_bank
module_end

* Global variables after the code in low expansion memory.
    dorg expansion_data_start

* HUD variables.
hud_sprite  data 0 ; Supersprite number to be shown in the HUD.
hud_counter data 0 ; Counter for the display time of the HUD.

* Weapons.
stone   equ 0
emp     equ 1
grenade equ 2

collectible_counts
medkit_count  data 0 ; Number of available medkits.
weapon_counts
stone_count   data 0 ; Number of available stones.
emp_count     data 0 ; Number of available EMPs.
grenade_count data 0 ; Number of available grenades.

weapon        data 0 ; The selected weapon type (0, 1, or 2).

collectible_counts_end

collectible_counts_size equ collectible_counts_end - collectible_counts

* Thrown stone variables.
weapon_states
stone_state
stone_x         data 0 ; X ordinate, expressed in pixels.
stone_y         data 0 ; Y ordinate, expressed in pixels.
stone_fx        data 0 ; Fractional x ordinate (fixed point 16.16 bits).
stone_fy        data 0 ; Fractional y ordinate (fixed point 16.16 bits).
stone_direction data 0 ; Direction (0..15).
stone_counter   data 0 ; Counter for the life time of the stone.
                bss  4 ; Filler to a data block of 8 words.

* Fired EMP variables.
emp_state
emp_x         data 0 ; X ordinate, expressed in pixels.
emp_y         data 0 ; Y ordinate, expressed in pixels.
emp_fx        data 0 ; Fractional x ordinate (fixed point 16.16 bits).
emp_fy        data 0 ; Fractional y ordinate (fixed point 16.16 bits).
emp_direction data 0 ; Direction (0..15).
emp_counter   data 0 ; Counter for the life time of the EMP.
              bss  4 ; Filler to a data block of 8 words.

* Thrown grenade variables.
grenade_state
grenade_x         data 0 ; X ordinate, expressed in pixels.
grenade_y         data 0 ; Y ordinate, expressed in pixels.
grenade_fx        data 0 ; Fractional x ordinate (fixed point 16.16 bits).
grenade_fy        data 0 ; Fractional y ordinate (fixed point 16.16 bits).
grenade_direction data 0 ; Direction (0..15).
grenade_counter   data 0 ; Counter for the life time of the grenade.
                  bss  4 ; Filler to a data block of 8 words.

* Turret bullet variables.
bullet_state
bullet_x         data 0 ; X ordinate, expressed in pixels.
bullet_y         data 0 ; Y ordinate, expressed in pixels.
bullet_fx        data 0 ; Fractional x ordinate (fixed point 16.16 bits).
bullet_fy        data 0 ; Fractional y ordinate (fixed point 16.16 bits).
bullet_direction data 0 ; Direction (0..15).
bullet_counter   data 0 ; Counter for the life time of the bullet.

* Launched shell variables.
shell_state
shell_x       data 0 ; X ordinate, expressed in pixels.
shell_y       data 0 ; Y ordinate, expressed in pixels.
shell_fx      data 0 ; Fractional x ordinate (fixed point 16.16 bits).
shell_fy      data 0 ; Fractional y ordinate (fixed point 16.16 bits).
shell_dx      data 0 ; X speed, expressed in pixels per frame.
shell_dy      data 0 ; Y speed, expressed in pixels per frame.
shell_dfx     data 0 ; Fractional x speed (fixed point 16.16 bits).
shell_dfy     data 0 ; Fractional y speed (fixed point 16.16 bits).
shell_counter data 0 ; Counter for the life time of the shell.

* Landscape display variables.
previous_landscape_patterns_offset data 0 ; Most recently drawn landscape patterns source offset.
previous_quadrant_x                data 0 ; Most recently drawn landscape quadrant ordinates,
previous_quadrant_y                data 0 ; expressed as multiples of 4 pixels.

* Mouse variables.
mouse_present data 0 ; Mouse present or not (>0000).
mouse_x       data 0 ; Mouse x ordinate around player.
mouse_y       data 0 ; Mouse y ordinate around player.

* Keyboard variables.
keyboard_repeat data 0 ; Keyboard turn autorepeat counter.

    .print 'Unused bytes in low expansion memory:', low_expansion_memory_end - $

    .ifgt  $, low_expansion_memory_end
    .error 'Data structures too large for low expansion memory'
    .endif

* Global variables in high expansion memory.
    dorg high_expansion_memory

* Object lists. We have a set of object data per horizontal strip of 128 pixels
* high. All coordinates in the lists are those of the top-left corner of a
* virtual screen in the world, compatible with the player coordinates.
object_strip_pixel_height       equ 128 ; Number of pixels vertically per strip.
object_strip_pixel_height_shift equ 7   ; The corresponding bit shift.

object_strip_size         equ 256 ; Bytes of data per strip.
object_strip_size_shift   equ 8   ; The corresponding bit shift.

world_character_height    equ 512 ; Number of characters vertically in the world.
world_pixel_height        equ world_character_height * 8 ; Number of pixels vertically in the world.

object_strip_count        equ world_pixel_height / object_strip_pixel_height ; Number of strips.
object_states_size        equ object_strip_count * object_strip_size         ; Total size of all strips.

* Maximum numbers of objects per strip.
max_target_count          equ  1
max_mine_count            equ  3
max_drone_count           equ  3
max_launcher_count        equ  3
max_turret_count          equ  3
max_collectible_count     equ  8
max_message_count         equ  4
max_background_count      equ 12

* Reserve space for the first strip of object lists.
* Each list has a terminator word.
object_states
targets                   bss max_target_count * 4 + 2      ; X ordinate, y ordinate.
mines                     bss max_mine_count * 6 + 2        ; X ordinate, y ordinate, explosion.
drones                    bss max_drone_count * 10 + 2      ; X ordinate, y ordinate, fractional x ordinate, fractional y ordinate, direction (0..15 = 4 bits).
launchers                 bss max_launcher_count * 6 + 2    ; X ordinate, y ordinate, explosion.
turrets                   bss max_turret_count * 6 + 2      ; X ordinate, y ordinate, direction (0..15 = 4 bits).
collectibles              bss max_collectible_count * 6 + 2 ; X ordinate, y ordinate, type.
messages                  bss max_message_count * 6 + 2     ; X ordinate, y ordinate, number.
background_objects        bss max_background_count * 6 + 2  ; X ordinate, y ordinate, type.
first_object_states_end
                                                            ; Filler to get to the strip size.
                          bss object_strip_size + object_states - first_object_states_end

    .ifgt first_object_states_end - object_states, object_strip_size
    .error 'Incorrect strip size.'
    .endif

* Reserve space for the remaining strips of object lists.
                          bss object_states_size - object_strip_size
object_states_end

* Saved states.
saved_player_state       bss player_state_size
saved_collectible_counts bss collectible_counts_size
saved_object_states      bss object_states_size

* Player start position (initial or most recently reached target). The
* coordinates are those of the top-left corner of a virtual screen in the
* world, compatible with the player coordinates.
saved_player_x equ saved_player_state + 0 ; Saved X ordinate, expressed in pixels.
saved_player_y equ saved_player_state + 2 ; Saved Y ordinate, expressed in pixels.

* Supersprite/quadsprite cache pointers.
vdp_quadsprite_numbers    bss 1024 * 2 ; The VDP quadsprite number (0..63 = 6 bits, shifted left 1 bit) for each CPU ROM quadsprite number (0..1023).
cpu_quadsprite_numbers    bss 64 * 2   ; The CPU ROM quadsprite number (0..1023, shifted left 1 bit) for each VDP quadsprite number (0..63).
vdp_quadsprite_timestamps bss 64 * 2   ; The timestamp of the most recent frame for each VDP quadsprite number (0..63).
sprite_cache_queue        bss 32 * 2   ; The queue with CPU quadsprite numbers (shifted left 1 bit) to be written to VDP memory.
                                       ; TODO: The queue may overflow.

    .print 'Unused bytes in high expansion memory:', -$

    .iflt  $, >8000
    .error 'Data structures too large for high expansion memory'
    .endif

* The memory bank addresses: >6000, >6002,.... (multiples of 2).
    dorg module_bank_selection

code_bank                        bss 2 * 1
data_bank                        bss 2 * 1
intro_video_bank                 bss 2 * 4
dying_player_animation_banks     bss 2 * 16
crouching_player_animation_banks bss 2 * 16
standing_player_animation_banks  bss 2 * 9 * 16
landscape_objects_bank           bss 2 * 1
landscape_characters_banks       bss 2 * 32
landscape_mask_bank              bss 2 * 1
sprite_bounds_bank               bss 2 * 1
sprite_index_bank                bss 2 * 1
sprite_positions_banks           bss 2 * 4
sprite_patterns_banks            bss 2 * 2
speech_data_bank                 bss 2 * 1

    .ifne  module_start + (($ & >00fe) * >1000), module_end + >1fff & >e000
    .error 'Incorrect memory bank addresses.'
    .endif
